# Questions # : 5,9,29,31,34,35,32,23,46,50,39,43,30,37,47,64

5.Display full name of patients who are born in 1986

In [1]:
import pandas as pd
import numpy as np

In [2]:
#reading patients data
df1 = pd.read_excel('HospitalDatabase.xlsx') 
#df1.info()
#extracting year from date of birth
df1['year'] = df1['DateOfBirth'].dt.year
#extracting firstname and lastname whose dob is 1986
names = (df1['FirstName'] + df1 ['LastName']).where (df1['year'] == 1986)
names.dropna()

23         Gabriel Joseph
24         Lincoln Brenda
29             AlaHalpert
72            LolitaDarci
164         FadelBernardt
238         BentleyKippax
367            ValeOlanda
373          BrittDureden
386       CristabelChatel
415       ConstantiaGroup
452       MorganScrowston
561             DomBaglow
568        IgnazioMelling
595         HomenickRings
639           HashimSlark
643       EllieRamsbotham
674        LlewellynGroup
714             NilesShaw
733             YvetteInc
777          SiouxieGroup
852            CarlyGroup
868        WorthPickering
877           ArniBaldack
909       KuvalisCoupland
922    RebbeccaRollingson
940            WatFideler
dtype: object

9.Get the list of patient ids which are not there in ReadmissionRegistry

In [3]:
df = pd.read_excel('HospitalDatabase.xlsx',sheet_name = 'ReAdmissionRegistry')
df['PatientID'].unique()
df1['PatientID'].unique() 
df1['NoReadmit'] = ~df1.PatientID.isin(df.PatientID)
NoReadmit = df1['PatientID'].where(df1['NoReadmit']== True).dropna().astype(int)
NoReadmit.unique().tolist()

[4,
 135,
 145,
 189,
 200,
 224,
 234,
 374,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 414,
 501,
 562,
 599,
 690,
 691,
 704,
 726,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,


29.Calculate average LOS

In [4]:
df3 =  pd.read_excel('HospitalDatabase.xlsx',sheet_name = 'Discharges')
df3['ExpectedLOS'].mean()

8.82458915915616

In [5]:
df['ExpectedLOS'].mean()

8.824589159156156

31.Find count of White Spanish Male

In [6]:
print("The count of White Spanish Male is ",len(df1.loc[(df1['Language'] == 'Spanish') & (df1['Gender'] == 'Male') & (df1['Race']== 'White')]))

The count of White Spanish Male is  15


34.np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17

In [7]:
x = np.arange(1,31).reshape(6,5)
x[2:4,0:2]

array([[11, 12],
       [16, 17]])

35.np.arange(1,31).reshape(6,5), find array slicing for elements 2,8,14,20

In [8]:
y = np.arange(1,31).reshape(6,5)
np.diagonal(y[0:4,1:5])

array([ 2,  8, 14, 20])

32.Write a function to print the table of the given number

In [9]:
number = int(input("Enter the number: "))
for count in range(1, 11):
    print(number, 'x', count, '=', number * count)

Enter the number: 11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110


23.Function to find the center element in the list. (1 element in odd length list, 2 elements in even length list)

In [11]:
lst = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst.append(ele)  
print(lst)
if len(lst) % 2 != 0 :
    print("Center element is ",lst[int(len(lst)/2)])
else:
    print("Center elements are ",(lst[int(((len(lst))-1)/2)],lst[int(len(lst)/2)]))

Enter number of elements : 5
99
33
11
22
44
[99, 33, 11, 22, 44]
Center element is  11


46.Write a code to split a sentence into words using regex

In [12]:
import re
sentence = 'This is numpyninja hackathon'
words = re.split(' ',sentence)
words

['This', 'is', 'numpyninja', 'hackathon']

50.Which departmentID has maximum number of visits scheduled.

In [13]:
df4 = pd.read_excel('HospitalDatabase.xlsx',sheet_name = 'AmbulatoryVisits')
print('Department with maximum number of visits scheduled is ',df4['VisitDepartmentID'].value_counts().idxmax())

Department with maximum number of visits scheduled is  11


39.Get the FirstName, LastName,DateOfBirth of the Patients whose reason for visit is Migraine. 
Use EDUnique Sheet for reason for visit

In [14]:
df5 = pd.read_excel('HospitalDatabase.xlsx',sheet_name = 'EDUnique')
Migraine_df = pd.merge(df1, df5, on = 'PatientID')
Migraine_df1 = Migraine_df.loc[Migraine_df['ReasonForVisit'] == 'Migraine']
Migraine_df1[['FirstName','LastName','DateOfBirth','ReasonForVisit']]

FirstName  LastName             DateOfBirth ReasonForVisit
1         Far     Myers 1985-11-15 02:08:42.090       Migraine
2     Devlin    Michael 1976-04-15 02:52:09.762       Migraine
11     Zonnya        Ab 1963-05-23 10:04:33.074       Migraine
13        Gan        Yu 1970-06-02 06:22:54.675       Migraine
21     Joesph      Long 1979-12-04 16:45:56.080       Migraine
..        ...       ...                     ...            ...
896   Barrows  Coupland 1979-10-31 18:28:35.483       Migraine
907      Knox     Group 1975-08-25 22:27:50.177       Migraine
909   Kuvalis  Coupland 1986-05-23 19:23:27.752       Migraine
914  Jerrilyn     Dyson 1978-01-18 02:41:55.178       Migraine
923    Daniel  Shakesby 1980-11-28 17:57:03.702       Migraine

[116 rows x 4 columns]

43.Write a regular expression to find all the digits and numbers in the string

In [15]:
import re
def findNumbers(str):
    array = re.findall(r'[0-9]+', str)
    return array
  
str = "a1b2c3e4d5e6f7g8h9"
array = findNumbers(str)
print(*array)

1 2 3 4 5 6 7 8 9


30.Which patientid has most entries in readmission registry

In [16]:
print("The Patient Id with most entries in readmission registry is ",df['PatientID'].value_counts().idxmax())

The Patient Id with most entries in readmission registry is  23


37.Write a function to print all the upper case letter of a given sentence

In [17]:
sentence = "Numpy Ninja HAcKathon"
caps = list(filter(lambda c: c.isupper(), sentence)) 
print("The uppercase characters in are : " ,caps)

The uppercase characters in are :  ['N', 'N', 'H', 'A', 'K']


47.Using indexing ,loc ,retrieve the row with maximum BloodPressureSystolic

In [18]:
df4.loc[df4.BloodPressureSystolic == df4.BloodPressureSystolic.max()]

VisitID  PatientMRN  ProviderID DateofVisit           DateScheduled  \
236      933         884          27  2019-02-14 2019-01-22 19:26:49.163   
251      888         906          24  2019-03-31 2019-03-17 23:21:17.361   
424      314          63           7  2019-04-05 2019-03-24 22:31:26.092   
432      740         892          31  2019-03-14 2019-03-11 15:08:33.963   
677      929         880          23  2019-02-10 2019-01-22 13:32:14.549   
869      839         857          12  2019-03-17 2019-02-23 09:05:43.676   
934      482         866          14  2019-05-04 2019-04-13 07:54:49.580   

     VisitDepartmentID     VisitType  BloodPressureSystolic  \
236                 12  Telemedicine                  190.0   
251                 10           New                  190.0   
424                 11  Telemedicine                  190.0   
432                  8      Physical                  190.0   
677                  8     Follow Up                  190.0   
869                  8     Follow Up                  190.0   
934                  5           New                  190.0   

     BloodPressureDiastolic      Pulse VisitStatus  
236              143.989174  74.976879   Completed  
251              137.207999  52.666922   Completed  
424              121.539859  95.471260   Completed  
432              145.343479  94.849021   Completed  
677              144.313400  82.781940   Completed  
869              130.997386  71.829542   Completed  
934              124.736359  69.731779    Canceled

64."Using numpy functions, multiply the following arrays
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(3,2)"

In [19]:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(3,2)
np.dot(a,b)
np.matmul(a,b)
a

array([[0, 1, 2],
       [3, 4, 5]])